name: swap_flutter
description: "Swap Neobank Flutter App - Local-first financial application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.3

  # HTTP Client & API
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

  # Local Database (Local-first architecture)
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0

  # Secure Storage & Authentication
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1

  # Background Tasks & Sync
  workmanager: ^0.5.2

  # Connectivity & Network
  connectivity_plus: ^6.0.3
  network_info_plus: ^5.0.3

  # UI & Design System
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # Utilities
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  uuid: ^4.4.0
  intl: ^0.19.0
  logger: ^2.3.0

  # Maps (for geospatial features)
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Biometric Authentication
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.1.0
  drift_dev: ^2.18.0

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  
  # Fonts (if needed for custom typography)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
